### ISSUE TITLE
It fails on filenames with spaces

### ISSUE THREAD

**Issue by j605** [fmoralesc/nlanguagetool#2]

**Comment by fmoralesc** [comment]
Can you confirm that changing line 9 of `autoload/nlanguagetool.vim` to

``` vim
    let call_s = 'languagetool --disablecategories TYPOGRAPHY --json ' . fnameescape(fname) . ' > ' . tmpfile
```
fixes it? If so, I'll push the change right away.

**Comment by j605** [comment]
Yes that fixes the issue, thanks :)

**Comment by fmoralesc** [comment]
OK, then, I just pushed the change to master ;)
